#!/usr/bin/env bash
# displays information about subdomains
func () {
	FULLSUB="${1}.iamthenight.tech"
	dig $FULLSUB | awk -v subd="$1" '/ANSWER SECTION:/{getline; print "The subdomain "subd" is a "$4" record and points to "$5}'
}

if [ "$#" -lt 2 ]
then
	func "www"
	func "lb-01"
	func "web-01"
	func "web-02"
else
	func "$2"
fi
