#!/usr/bin/env bash
# configures nginx with custom 404 page
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/my_404.html
err_pg="\terror_page 404 /my_404.html;\n\tlocation /my_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -r -i "/^\s+server_name .+;/a\ $err_pg" /etc/nginx/sites-available/default
service nginx restart
