#!/usr/bin/env bash
# configures nginx
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html

redir="\n\tlocation /redirect_me {\n\t\treturn 301 https://bit.ly/3rTuCnC;\n\t}"
sed -r -i "/^\s+server_name .+;/a\ $redir" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/my_404.html
err_pg="\n\terror_page 404 /my_404.html;\n\tlocation /my_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sed -r -i "/^\s+server_name .+;/a\ $err_pg" /etc/nginx/sites-available/default

served_by="\n\tadd_header X-Served-By $HOSTNAME;"
sed -r -i "/^\s+server_name .+;/a\ $served_by" /etc/nginx/sites-available/default

service nginx restart
