#!/usr/bin/env bash
# configures haproxy with roundrobin load balancing
apt-get -y update
apt-get -y install haproxy
echo -e '
frontend http-in
\tbind *:80
\tdefault_backend web-backend

backend web-backend
\tbalance roundrobin
\tserver 2331-web-01 34.73.71.111:80 check
\tserver 2331-web-02 3.91.201.53:80 check
' | tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
