#!/usr/bin/env bash
# displays message indefinitely
pgrep 100-process_and_pid_file > /var/run/holbertonscript.pid
trap 'echo Y U no love me?!; trap - SIGINT; kill -SIGINT $$' SIGINT
trap 'echo I hate the kill command; rm /var/run/holbertonscript.pid
     trap - SIGTERM; kill -SIGTERM $$' SIGTERM
trap 'rm /var/run/holbertonscript.pid; trap - SIGQUIT
     kill -SIGKILL $$' SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
